name = "landing-prosperify"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"

[site]
bucket = ".open-next/assets"

# 👇 Force le mapping des fichiers statiques (_next/*) vers ton bucket
[[routes]]
pattern = "prosperify.app/_next/*"
zone_name = "prosperify.app"

[[routes]]
pattern = "prosperify.app/*"
zone_name = "prosperify.app"
